GET http://localhost:3000/usuarios
###
GET http://localhost:3000/usuarios/1
###
POST http://localhost:3000/usuarios/
Content-Type: application/json

{
    "nombre": "Cristino",
    "apellido": "Teodoro San Juan",
    "email": "cristino@gmail.com"
}
###
PUT http://localhost:3000/usuarios/1
Content-Type: application/json

{
    "nombre": "Cristino",
    "apellido": "Teodoro Pavon",
    "email": "teodoropavonjuan@gmail.com"
}
###
PATCH http://localhost:3000/usuarios/1
content-type: application/json

{
  "nombre": "Carlos"
}

###
DELETE http://localhost:3000/usuarios/1